# Customer Data Cleaning

## Objective

Clean and validate customer master data before loading into the analytics database.

## Cleaning Tasks

- Identify missing values
- Remove duplicate customer IDs
- Standardize customer channels
- Correct regional inconsistencies
- Validate customer records

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
raw_path = Path("../data/raw/customers.csv")

clean_path = Path("../data/cleaned/customers_clean.csv")

In [3]:
customers = pd.read_csv(raw_path)

customers.head()

,customer_id,customer_name,customer_type,channel,city,state,region
0,1,Midwest Beverage Partners,Distributor,Distributor,Chicago,IL,Midwest
1,2,Kroger,Grocery,Grocery,Cincinnati,OH,Midwest
2,3,Walmart,Retail,Retail,Bentonville,AR,South
3,4,7-Eleven,Convenience,Convenience,Irving,TX,South
4,5,Walgreens,Retail,Retail,Deerfield,IL,Midwest

In [4]:
customers.shape

(500, 7)

In [5]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    500 non-null    int64
 1   customer_name  498 non-null    object
 2   customer_type  500 non-null    object
 3   channel        500 non-null    object
 4   city           500 non-null    object
 5   state          500 non-null    object
 6   region         500 non-null    object
dtypes: int64(1), object(6)
memory usage: 27.5+ KB

In [6]:
customers.isnull().sum()

customer_id      0
customer_name    2
customer_type    0
channel          0
city             0
state            0
region           0
dtype: int64

In [7]:
customers.duplicated().sum()

0

In [8]:
customers["customer_id"].duplicated().sum()

1

In [9]:
customers[
    customers["customer_id"].duplicated(keep=False)
]

,customer_id,customer_name,customer_type,channel,city,state,region
299,300,Casey's General Store,Convenience,Convenience,Ankeny,IA,Midwest
300,300,KeHE,Distributor,Distributor,Naperville,IL,Midwest

In [11]:
customers_clean = customers.copy()

In [12]:
customers_clean["customer_name"] = (
    customers_clean["customer_name"]
    .fillna("Unknown Customer")
)

In [13]:
customers_clean["customer_id"].max()

500

In [15]:
customers_clean.loc[
    customers_clean["customer_id"].duplicated(),
    "customer_id"
] = customers_clean["customer_id"].max() + 1

In [16]:
customers_clean["customer_id"].duplicated().sum()

0

In [17]:
customers_clean["channel"].value_counts()

channel
Retail         157
Distributor    146
Convenience    128
Grocery         69
Name: count, dtype: int64

In [18]:
customers_clean["region"].value_counts()

region
Midwest      184
West         139
Northeast     81
South         68
Mountain      26
Wesst          1
Northeest      1
Name: count, dtype: int64

In [19]:
region_mapping = {
    "Wesst": "West",
    "Northeest": "Northeast"
}

customers_clean["region"] = (
    customers_clean["region"]
    .replace(region_mapping)
)

In [20]:
customers_clean["region"].value_counts()

region
Midwest      184
West         140
Northeast     82
South         68
Mountain      26
Name: count, dtype: int64

In [21]:
customers_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    500 non-null    int64
 1   customer_name  500 non-null    object
 2   customer_type  500 non-null    object
 3   channel        500 non-null    object
 4   city           500 non-null    object
 5   state          500 non-null    object
 6   region         500 non-null    object
dtypes: int64(1), object(6)
memory usage: 27.5+ KB

In [22]:
customers_clean.isnull().sum()

customer_id      0
customer_name    0
customer_type    0
channel          0
city             0
state            0
region           0
dtype: int64

In [23]:
customers_clean.to_csv(
    clean_path,
    index=False
)

## Summary

The customer dataset was cleaned and validated by:

- Handling missing customer names
- Resolving duplicate customer identifiers
- Validating channel categories
- Correcting regional inconsistencies
- Confirming data completeness

The cleaned dataset is ready for downstream analytics and database loading.